#!/usr/bin/env ts-node
/**
 * sync-content-types.ts
 *
 * Reads shared/content-types.json → generates src/generated/content-types.ts
 *
 * Usage:
 *   npm run sync:content-types          # generate / overwrite
 *   npm run sync:content-types -- --check  # CI: exit 1 if out of sync
 */
import fs from 'fs'
import path from 'path'

const ROOT    = path.resolve(__dirname, '../..')
const SOURCE  = path.join(ROOT, 'shared', 'content-types.json')
const TARGET  = path.resolve(__dirname, '../src/generated/content-types.ts')
const CHECK   = process.argv.includes('--check')

interface ContentTypeEntry {
  canonical: string
  compositions: Record<string, string>
  aliases: string[]
}

function generate(types: ContentTypeEntry[]): string {
  const aliasLines: string[] = []
  const mapLines: string[] = []

  for (const ct of types) {
    const allNames = [ct.canonical, ...ct.aliases]

    // CONTENT_TYPE_ALIASES — canonical maps to itself implicitly
    for (const alias of ct.aliases) {
      aliasLines.push(`  "${alias}":${''.padEnd(Math.max(1, 24 - alias.length))} "${ct.canonical}",`)
    }

    // COMPOSITION_MAP — default + aspect-specific
    const defaultComp = ct.compositions['default']
    for (const name of allNames) {
      mapLines.push(`  "${name}":${''.padEnd(Math.max(1, 28 - name.length))} "${defaultComp}",`)
      for (const [aspect, comp] of Object.entries(ct.compositions)) {
        if (aspect === 'default') continue
        const key = `${name}:${aspect}`
        mapLines.push(`  "${key}":${''.padEnd(Math.max(1, 28 - key.length))} "${comp}",`)
      }
    }
  }

  return `// AUTO-GENERATED by scripts/sync-content-types.ts — do not edit manually.
// Source: ../shared/content-types.json
// To regenerate: npm run sync:content-types
// To verify in CI: npm run sync:content-types -- --check

/** alias → canonical content type name */
export const CONTENT_TYPE_ALIASES: Record<string, string> = {
${aliasLines.join('\n')}
}

/** (canonical-or-alias)[:aspect] → Remotion composition ID */
export const COMPOSITION_MAP: Record<string, string> = {
${mapLines.join('\n')}
  // ── quiz_board — Root.tsx'de kayıtlı, canonical dışı ─────────
  "quiz_board":               "QuizBoardVideo",
  "quiz_board:16:9":          "QuizBoardVideo",
}
`
}

function main() {
  if (!fs.existsSync(SOURCE)) {
    console.error(`[sync] HATA: ${SOURCE} bulunamadı`)
    process.exit(1)
  }

  const raw = JSON.parse(fs.readFileSync(SOURCE, 'utf-8'))
  const generated = generate(raw.types as ContentTypeEntry[])

  if (CHECK) {
    if (!fs.existsSync(TARGET)) {
      console.error('[sync] CHECK FAILED: generated file yok, sync:content-types çalıştırın')
      process.exit(1)
    }
    const current = fs.readFileSync(TARGET, 'utf-8')
    if (current !== generated) {
      console.error('[sync] CHECK FAILED: content-types.ts kaynakla senkronize değil, sync:content-types çalıştırın')
      process.exit(1)
    }
    console.log('[sync] CHECK OK: content-types.ts güncel')
    return
  }

  const dir = path.dirname(TARGET)
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(TARGET, generated, 'utf-8')
  console.log(`[sync] generated → ${path.relative(ROOT, TARGET)}`)
}

main()
