#!/usr/bin/env python3
"""
generate_content_constants.py

Reads shared/content-types.json → generates app/core/generated_constants.py

Docker build context'i backend/ (Railway Root Directory) olduğu için
shared/ imajda YOK — runtime'da o dosyayı okumaya çalışmak import-time
crash'e yol açar (aynı sınıf hata remotion bridge'de zaten yaşanmıştı,
bkz. remotion/scripts/sync-content-types.ts). Bu script CI/lokalde
çalışır, ürettiği .py dosyası git'e eklenir ve Docker imajına COPY . .
ile dahil olur — runtime'da shared/'a hiç dokunulmaz.

Kullanım:
  python backend/scripts/generate_content_constants.py           # üret / üzerine yaz
  python backend/scripts/generate_content_constants.py --check   # CI: senkron değilse exit 1
"""
import json
import sys
from pathlib import Path

ROOT   = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared" / "content-types.json"
TARGET = Path(__file__).resolve().parents[1] / "app" / "core" / "generated_constants.py"
CHECK  = "--check" in sys.argv


def generate(constants: dict) -> str:
    lines = [
        "# AUTO-GENERATED by backend/scripts/generate_content_constants.py — do not edit manually.",
        "# Source: ../../shared/content-types.json",
        "# To regenerate: python backend/scripts/generate_content_constants.py",
        "# To verify in CI: python backend/scripts/generate_content_constants.py --check",
        "",
    ]
    for key, value in constants.items():
        if key.endswith("_note"):
            continue
        if isinstance(value, str):
            lines.append(f'{key}: str = {value!r}')
        else:
            lines.append(f"{key}: float = {value!r}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not SOURCE.exists():
        print(f"[generate] HATA: {SOURCE} bulunamadı", file=sys.stderr)
        sys.exit(1)

    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    generated = generate(raw.get("constants", {}))

    if CHECK:
        if not TARGET.exists():
            print("[generate] CHECK FAILED: generated_constants.py yok, generate_content_constants.py çalıştırın", file=sys.stderr)
            sys.exit(1)
        current = TARGET.read_text(encoding="utf-8")
        if current != generated:
            print("[generate] CHECK FAILED: generated_constants.py kaynakla senkronize değil, generate_content_constants.py çalıştırın", file=sys.stderr)
            sys.exit(1)
        print("[generate] CHECK OK: generated_constants.py güncel")
        return

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(f"[generate] uretildi -> {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
