#!/usr/bin/env python3
"""
generate_content_constants.py

Reads shared/content-types.json → generates app/core/generated_constants.py

Docker build context'i backend/ (Railway Root Directory) olduğu için
shared/ imajda YOK — runtime'da o dosyayı okumaya çalışmak import-time
crash'e yol açar (aynı sınıf hata remotion bridge'de zaten yaşanmıştı,
bkz. remotion/scripts/sync-content-types.ts). Bu script CI/lokalde
çalışır, ürettiği .py dosyası git'e eklenir ve Docker imajına COPY . .
ile dahil olur — runtime'da shared/'a hiç dokunulmaz.

Kullanım:
  python backend/scripts/generate_content_constants.py           # üret / üzerine yaz
  python backend/scripts/generate_content_constants.py --check   # CI: senkron değilse exit 1
"""
import json
import sys
from pathlib import Path

ROOT   = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared" / "content-types.json"
TARGET = Path(__file__).resolve().parents[1] / "app" / "core" / "generated_constants.py"
CHECK  = "--check" in sys.argv


def generate(raw: dict) -> str:
    constants = raw.get("constants", {})
    types = raw.get("types", [])

    lines = [
        "# AUTO-GENERATED by backend/scripts/generate_content_constants.py — do not edit manually.",
        "# Source: ../../shared/content-types.json",
        "# To regenerate: python backend/scripts/generate_content_constants.py",
        "# To verify in CI: python backend/scripts/generate_content_constants.py --check",
        "",
    ]
    for key, value in constants.items():
        if key.endswith("_note"):
            continue
        if isinstance(value, str):
            lines.append(f'{key}: str = {value!r}')
        else:
            lines.append(f"{key}: float = {value!r}")

    lines.append("")
    lines.append("# canonical content_type -> {min_visual_surfaces, min_photos, max_photos?}")
    lines.append("VISUAL_SURFACE_MINIMUMS: dict[str, dict] = {")
    for t in types:
        entry = {
            "min_visual_surfaces": t.get("min_visual_surfaces"),
            "min_photos": t.get("min_photos"),
        }
        if "max_photos" in t:
            entry["max_photos"] = t["max_photos"]
        lines.append(f"    {t['canonical']!r}: {entry!r},")
    lines.append("}")
    lines.append("")

    lines.append("# canonical content_type -> {default, min, max} hedef süre (saniye) — yalnızca")
    lines.append("# tanımlı olan türler için (henüz hepsinde yok, veri uydurulmaz)")
    lines.append("TYPE_DURATIONS: dict[str, dict] = {")
    for t in types:
        if "duration" in t:
            lines.append(f"    {t['canonical']!r}: {t['duration']!r},")
    lines.append("}")
    lines.append("")

    lines.append("# canonical content_type -> doğal sahne süresi (sn) — scene_count_for_budget'ın")
    lines.append("# tek kaynağı. Tür bazlı: her türün içerik yoğunluğu farklı (görsel mi anlatıyor,")
    lines.append("# yalnızca söz mü taşıyor) — bkz. content-types.json *_note alanları.")
    lines.append("NATURAL_SCENE_SECONDS: dict[str, float] = {")
    for t in types:
        if "natural_scene_seconds" in t:
            lines.append(f"    {t['canonical']!r}: {t['natural_scene_seconds']!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not SOURCE.exists():
        print(f"[generate] HATA: {SOURCE} bulunamadı", file=sys.stderr)
        sys.exit(1)

    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    generated = generate(raw)

    if CHECK:
        if not TARGET.exists():
            print("[generate] CHECK FAILED: generated_constants.py yok, generate_content_constants.py çalıştırın", file=sys.stderr)
            sys.exit(1)
        current = TARGET.read_text(encoding="utf-8")
        if current != generated:
            print("[generate] CHECK FAILED: generated_constants.py kaynakla senkronize değil, generate_content_constants.py çalıştırın", file=sys.stderr)
            sys.exit(1)
        print("[generate] CHECK OK: generated_constants.py güncel")
        return

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(f"[generate] uretildi -> {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
