# AUTO-GENERATED by backend/scripts/generate_content_constants.py — do not edit manually.
# Source: ../../shared/content-types.json
# To regenerate: python backend/scripts/generate_content_constants.py
# To verify in CI: python backend/scripts/generate_content_constants.py --check

TR_SPS: float = 4.15
CHARS_PER_SYLLABLE: float = 2.7
