# AUTO-GENERATED by backend/scripts/generate_content_constants.py — do not edit manually.
# Source: ../../shared/content-types.json
# To regenerate: python backend/scripts/generate_content_constants.py
# To verify in CI: python backend/scripts/generate_content_constants.py --check

TR_SPS: float = 4.42
CHARS_PER_SYLLABLE: float = 2.7

# canonical content_type -> {min_visual_surfaces, min_photos, max_photos?}
VISUAL_SURFACE_MINIMUMS: dict[str, dict] = {
    'konu_anlatimi': {'min_visual_surfaces': 12, 'min_photos': 0},
    'soru_cozum': {'min_visual_surfaces': 3, 'min_photos': 0},
    'reels_short': {'min_visual_surfaces': 5, 'min_photos': 0, 'max_photos': 2},
    'motivasyon': {'min_visual_surfaces': 7, 'min_photos': 5},
    'gorsel_post': {'min_visual_surfaces': 3, 'min_photos': 0},
}

# canonical content_type -> {default, min, max} hedef süre (saniye) — yalnızca
# tanımlı olan türler için (henüz hepsinde yok, veri uydurulmaz)
TYPE_DURATIONS: dict[str, dict] = {
    'motivasyon': {'default': 45, 'min': 30, 'max': 90},
}

# canonical content_type -> doğal sahne süresi (sn) — scene_count_for_budget'ın
# tek kaynağı. Tür bazlı: her türün içerik yoğunluğu farklı (görsel mi anlatıyor,
# yalnızca söz mü taşıyor) — bkz. content-types.json *_note alanları.
NATURAL_SCENE_SECONDS: dict[str, float] = {
    'reels_short': 5.5,
    'motivasyon': 8.5,
}
